In [1]:
import pandas as pd
import numpy as np 

#Ignore harmless warnings 
import warnings 
warnings.filterwarnings("ignore")

#Set to display all the columns in dataset
pd.set_option("display.max_columns", None)

In [2]:
#Loading datasets
train_data = pd.read_csv(r"C:\Users\Charishma Gada\Desktop\bureau_assgn\Assignment_Train.csv", header=0)
test_data=pd.read_csv(r"C:\Users\Charishma Gada\Desktop\bureau_assgn\Assignment_Test.csv", header=0)

In [3]:
train_data.head()

,DEALER ID,APPLICATION LOGIN DATE,HDB BRANCH NAME,HDB BRANCH STATE,FIRST NAME,MIDDLE NAME,LAST NAME,mobile,AADHAR VERIFIED,Cibil Score,MOBILE VERIFICATION,DEALER NAME,TOTAL ASSET COST,ASSET CTG,ASSET MODEL NO,APPLIED AMOUNT,PRIMARY ASSET MAKE,Primary Asset Model No,Personal Email Address,MARITAL STATUS,GENDER,DOB,AGE,ADDRESS TYPE,EMPLOY CONSTITUTION,EMPLOYER NAME,EMPLOYER TYPE,Pan Name,name,vpa,upi_name,Phone Social Premium.a23games,Phone Social Premium.amazon,Phone Social Premium.byjus,Phone Social Premium.flipkart,Phone Social Premium.housing,Phone Social Premium.indiamart,Phone Social Premium.instagram,Phone Social Premium.isWABusiness,Phone Social Premium.jeevansaathi,Phone Social Premium.jiomart,Phone Social Premium.microsoft,Phone Social Premium.my11,Phone Social Premium.paytm,Phone Social Premium.rummycircle,Phone Social Premium.shaadi,Phone Social Premium.skype,Phone Social Premium.toi,Phone Social Premium.whatsapp,Phone Social Premium.yatra,Phone Social Premium.zoho,phone_digitalage,phone_nameMatchScore,phone_phoneFootprintStrengthOverall,Application Status
0,106989,07/20/2022,DELHI-SF,DELHI,SUNIL,NaN,CHANDER,9210574080,NO,726,True,V D AUTO WHEELS CHHOTIAL,95041.0,MCEXA,139542,85000,HONDA MOTORS,SHINE DRUM BSVI,SUNILSEHRAWAT7355@GMAIL.COM,Married,Male,1041978,44,Parental,SALARIED,sehrawat spare parts,SALARIED,SUNIL KUMAR,SUNIL CHANDER,ABFSPAY,SUNIL KUMAR,NaN,1.0,0.0,1.0,0.0,1.0,NaN,NaN,0.0,NaN,0.0,NaN,1.0,NaN,0.0,0.0,1.0,NaN,NaN,0.0,5324.0,67.222222,High,APPROVED
1,108975,07/28/2022,PATNA-SF,BIHAR,AMRIT,NaN,KUMAR,8877987018,NO,NaN,True,CHANDAN AUTOMOBILES 259 KGS TOWER,NaN,NaN,140208,90000,HERO MOTORS,SPLENDOR PLUS SELF DRUM BSVI I3S,NULL@GMAIL.COM,NaN,Male,1011997,25,NaN,NaN,NaN,NaN,AMRIT KUMAR,AMRIT KUMAR,OKSBI,Amrit Kumar,NaN,1.0,1.0,1.0,0.0,1.0,NaN,NaN,0.0,NaN,0.0,NaN,1.0,NaN,0.0,0.0,0.0,NaN,NaN,0.0,1998.0,100.000000,High,APPROVED
2,111004,07/15/2022,DARJEELING-SF,WEST BENGAL,ANIMESH,NaN,THAPA,8910862135,NO,737,True,KN VISION 53HILL CART ROAD,119436.0,SCEXA,160001,75000,TVS MOTOR CO,TVS NTORQ SUPER SQUAD EDITION BSVI,CHETTRIDIKSHA@GMAIL.COM,Single,Male,9081999,22,Self/Spouse Owned,SELF-EMPLOYED,Thapas shop,SELF-EMPLOYED,ANIMESH THAPA,ANIMESH THAPA,NaN,NaN,NaN,0.0,0.0,1.0,0.0,1.0,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,0.0,-1.0,-1.000000,Low,APPROVED
3,192020,07/04/22,SAHARANPUR-SF,UTTAR PRADESH,ADITYA,NaN,SINGH,9758428017,NO,713,True,MAHADEV AUTOMOBILES MANGLAUR,87000.0,MCECA,160832,78500,HERO MOTORS,SPLENDOR+ BLK ACCT SS DRUM I3S BSVI,ADITYA98@GAMIL.COM,Single,Male,3071998,24,Parental,SELF-EMPLOYED,agriculture farming,SELF-EMPLOYED,ADITYA KUMAR,ADITYA SINGH,PAYTM,Aditya Kumar,NaN,0.0,0.0,1.0,1.0,1.0,1.0,NaN,0.0,NaN,0.0,NaN,1.0,NaN,0.0,0.0,1.0,NaN,NaN,0.0,1998.0,72.777778,High,APPROVED
4,55095,07/15/2022,MODASA-SF,GUJARAT,PARMAR,HARESHBHAI,AMRUTBHAI,9687028486,NO,669,True,DWARKESH AUTO SHAMLAJI ROAD,NaN,NaN,174641,70000,HONDA MOTORS,DIO STD BSVI,PARMARHARESHBHAI1989@GMAIL.COM,NaN,Male,5071989,33,NaN,NaN,NaN,NaN,HARESHBHAI AMRUTBHAI PARMAR,PARMAR HARESHBHAI AMRUTBHAI,IKWIK,HARESHBHAI AMRUTBHAI,NaN,1.0,0.0,0.0,0.0,1.0,1.0,NaN,0.0,NaN,0.0,NaN,1.0,NaN,0.0,0.0,1.0,NaN,NaN,0.0,1998.0,68.095238,High,DECLINED

In [4]:
test_data.head()

,UID,DEALER ID,APPLICATION LOGIN DATE,HDB BRANCH NAME,HDB BRANCH STATE,FIRST NAME,MIDDLE NAME,LAST NAME,mobile,AADHAR VERIFIED,Cibil Score,MOBILE VERIFICATION,DEALER NAME,TOTAL ASSET COST,ASSET CTG,ASSET MODEL NO,APPLIED AMOUNT,PRIMARY ASSET MAKE,Primary Asset Model No,Personal Email Address,MARITAL STATUS,GENDER,DOB,AGE,ADDRESS TYPE,EMPLOY CONSTITUTION,EMPLOYER NAME,EMPLOYER TYPE,Pan Name,name,vpa,upi_name,Phone Social Premium.a23games,Phone Social Premium.amazon,Phone Social Premium.byjus,Phone Social Premium.flipkart,Phone Social Premium.housing,Phone Social Premium.indiamart,Phone Social Premium.instagram,Phone Social Premium.isWABusiness,Phone Social Premium.jeevansaathi,Phone Social Premium.jiomart,Phone Social Premium.microsoft,Phone Social Premium.my11,Phone Social Premium.paytm,Phone Social Premium.rummycircle,Phone Social Premium.shaadi,Phone Social Premium.skype,Phone Social Premium.toi,Phone Social Premium.whatsapp,Phone Social Premium.yatra,Phone Social Premium.zoho,phone_digitalage,phone_nameMatchScore,phone_phoneFootprintStrengthOverall
0,1844045271814558464,105615,07/12/22,HUBLI-SF,NaN,VENUGOPAL,H,BHARADHVAJ,7019759674,NO,757,True,SHANTESHA AUTO PVT LTD PB ROAD,95352.0,SCECA,143241,88000,HONDA MOTORS,ACTIVA 6G STD BSVI,NULLMAIL@GMAIL.COM,Married,Male,10081965,56,Self/Spouse Owned,SALARIED,LIFE LINE HOSPITAL,SALARIED,VENUGOPAL SHESHAGIRI RAO BHARADHVAJ,VENUGOPAL H BHARADHVAJ,OKHDFCBANK,H VENUGOPAL BHARADHVAJ,NaN,0.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,NaN,0.0,NaN,1.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,676,100.0,Medium
1,1840349097823778816,91593,07/14/2022,SATNA-SF,MADHYA PRADESH,SHIVDHAR,NaN,CHAUDHARY,7697884828,NO,750,True,YASH MOTORS PANNA ROAD,75371.0,MOECA,166536,75000,TVS MOTOR CO,XL 100 HD I TOUCH START WE BSVI,SHIV@GMAIL.COM,Married,Male,1011980,42,Parental,SELF-EMPLOYED,m/s shivdhar Kirana Store,SELF-EMPLOYED,SHIVDHAR CHAUDHARY,SHIVDHAR CHAUDHARY,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,0.0,897,-1.0,Low
2,1488102613362294272,74152,07/07/22,LUCKNOW-SF,UTTAR PRADESH,MANISH,NaN,VERMA,8840079825,NO,710,True,JP MOTOR PRIVATE LTD NEXT TO CARAK,94983.0,SCECA,134123,93000,HONDA MOTORS,ACTIVA 6G DLX,MANISHVERMA1996@GMAIL.COM,Single,Male,28091996,25,Self/Spouse Owned,SELF-EMPLOYED,RK TRADERS (OWNER),SELF-EMPLOYED,MANISH VERMA,MANISH VERMA,AXL,MANISH VERMA,NaN,1.0,0.0,1.0,0.0,1.0,NaN,0.0,0.0,NaN,1.0,NaN,1.0,NaN,0.0,1.0,0.0,1.0,NaN,0.0,839,100.0,Medium
3,555529923942874624,110164,07/13/2022,KOLLAM-SF,KERALA,DEEPU,RAVEENDRAN,RAVEENDRAN,8089276854,NO,695,True,GEORGE MAIJO INDUSTRIES P L ANANDAR,NaN,NaN,143627,95000,YAMAHA MOTOR,RAY ZR 125 FI DRUM BSVI,DEEPU@GMAIL.COM,NaN,Male,14041988,34,NaN,NaN,NaN,NaN,DEEPU RAVEENDRAN,DEEPU RAVEENDRAN RAVEENDRAN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,0.0,2050,-1.0,Low
4,1010213070486150912,113037,07/08/22,PURI-SF,ORISSA,AKASHA,NaN,PRADHAN,9337511958,NO,NaN,True,MAA HENGULA MOTORS BRAHMAGIRI,90277.0,MCECA,143948,83000,HERO MOTORS,PASSION PRO SS DRUM BRAKE BSVI,AKASHAPRADHAN@GMAIL.COM,Single,Male,1011998,24,Parental,SELF-EMPLOYED,KHETRAPALA SEA FOODS,SELF-EMPLOYED,NaN,AKASHA PRADHAN,YBL,AKASH PRADHAN,NaN,1.0,0.0,1.0,0.0,1.0,1.0,NaN,0.0,NaN,0.0,NaN,1.0,NaN,0.0,0.0,0.0,NaN,NaN,0.0,-1,-1.0,Very Low

In [5]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 55 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   DEALER ID                            10000 non-null  int64
 1   APPLICATION LOGIN DATE               10000 non-null  object
 2   HDB BRANCH NAME                      9999 non-null   object
 3   HDB BRANCH STATE                     9146 non-null   object
 4   FIRST NAME                           10000 non-null  object
 5   MIDDLE NAME                          2855 non-null   object
 6   LAST NAME                            9319 non-null   object
 7   mobile                               10000 non-null  int64
 8   AADHAR VERIFIED                      10000 non-null  object
 9   Cibil Score                          5703 non-null   object
 10  MOBILE VERIFICATION                  10000 non-null  bool
 11  DEALER NAME                          9996 non-null   object
 12  TOTAL ASSET COST                     4892 non-null   float64
 13  ASSET CTG                            4892 non-null   object
 14  ASSET MODEL NO                       10000 non-null  int64
 15  APPLIED AMOUNT                       10000 non-null  int64
 16  PRIMARY ASSET MAKE                   10000 non-null  object
 17  Primary Asset Model No               10000 non-null  object
 18  Personal Email Address               10000 non-null  object
 19  MARITAL STATUS                       5106 non-null   object
 20  GENDER                               10000 non-null  object
 21  DOB                                  10000 non-null  int64
 22  AGE                                  10000 non-null  int64
 23  ADDRESS TYPE                         6688 non-null   object
 24  EMPLOY CONSTITUTION                  5002 non-null   object
 25  EMPLOYER NAME                        4990 non-null   object
 26  EMPLOYER TYPE                        5002 non-null   object
 27  Pan Name                             8947 non-null   object
 28  name                                 10000 non-null  object
 29  vpa                                  7213 non-null   object
 30  upi_name                             7211 non-null   object
 31  Phone Social Premium.a23games        1 non-null      float64
 32  Phone Social Premium.amazon          8084 non-null   float64
 33  Phone Social Premium.byjus           8052 non-null   float64
 34  Phone Social Premium.flipkart        8168 non-null   float64
 35  Phone Social Premium.housing         8224 non-null   float64
 36  Phone Social Premium.indiamart       8225 non-null   float64
 37  Phone Social Premium.instagram       3370 non-null   float64
 38  Phone Social Premium.isWABusiness    1573 non-null   float64
 39  Phone Social Premium.jeevansaathi    8171 non-null   float64
 40  Phone Social Premium.jiomart         410 non-null    float64
 41  Phone Social Premium.microsoft       8128 non-null   float64
 42  Phone Social Premium.my11            2 non-null      float64
 43  Phone Social Premium.paytm           8243 non-null   float64
 44  Phone Social Premium.rummycircle     1 non-null      float64
 45  Phone Social Premium.shaadi          8221 non-null   float64
 46  Phone Social Premium.skype           8215 non-null   float64
 47  Phone Social Premium.toi             8057 non-null   float64
 48  Phone Social Premium.whatsapp        1573 non-null   float64
 49  Phone Social Premium.yatra           9 non-null      float64
 50  Phone Social Premium.zoho            8218 non-null   float64
 51  phone_digitalage                     9996 non-null   float64
 52  phone_nameMatchScore                 9996 non-null   float64
 53  phone_phoneFootprintStrengthOverall  9994 non-null   object
 54  Application Status                   10000 non-null  object
dtypes: bool(1), float64(23), int64(6), object(25)
memory usage: 4.1+ MB

In [6]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 55 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   UID                                  2000 non-null   int64
 1   DEALER ID                            2000 non-null   int64
 2   APPLICATION LOGIN DATE               2000 non-null   object
 3   HDB BRANCH NAME                      2000 non-null   object
 4   HDB BRANCH STATE                     1828 non-null   object
 5   FIRST NAME                           2000 non-null   object
 6   MIDDLE NAME                          595 non-null    object
 7   LAST NAME                            1869 non-null   object
 8   mobile                               2000 non-null   int64
 9   AADHAR VERIFIED                      2000 non-null   object
 10  Cibil Score                          1158 non-null   object
 11  MOBILE VERIFICATION                  2000 non-null   bool
 12  DEALER NAME                          2000 non-null   object
 13  TOTAL ASSET COST                     978 non-null    float64
 14  ASSET CTG                            978 non-null    object
 15  ASSET MODEL NO                       2000 non-null   int64
 16  APPLIED AMOUNT                       2000 non-null   int64
 17  PRIMARY ASSET MAKE                   2000 non-null   object
 18  Primary Asset Model No               2000 non-null   object
 19  Personal Email Address               2000 non-null   object
 20  MARITAL STATUS                       1019 non-null   object
 21  GENDER                               2000 non-null   object
 22  DOB                                  2000 non-null   int64
 23  AGE                                  2000 non-null   int64
 24  ADDRESS TYPE                         1365 non-null   object
 25  EMPLOY CONSTITUTION                  1006 non-null   object
 26  EMPLOYER NAME                        1005 non-null   object
 27  EMPLOYER TYPE                        1006 non-null   object
 28  Pan Name                             1791 non-null   object
 29  name                                 2000 non-null   object
 30  vpa                                  1446 non-null   object
 31  upi_name                             1445 non-null   object
 32  Phone Social Premium.a23games        0 non-null      float64
 33  Phone Social Premium.amazon          1883 non-null   float64
 34  Phone Social Premium.byjus           1977 non-null   float64
 35  Phone Social Premium.flipkart        1955 non-null   float64
 36  Phone Social Premium.housing         1977 non-null   float64
 37  Phone Social Premium.indiamart       1977 non-null   float64
 38  Phone Social Premium.instagram       612 non-null    float64
 39  Phone Social Premium.isWABusiness    262 non-null    float64
 40  Phone Social Premium.jeevansaathi    1962 non-null   float64
 41  Phone Social Premium.jiomart         43 non-null     float64
 42  Phone Social Premium.microsoft       1971 non-null   float64
 43  Phone Social Premium.my11            0 non-null      float64
 44  Phone Social Premium.paytm           1975 non-null   float64
 45  Phone Social Premium.rummycircle     0 non-null      float64
 46  Phone Social Premium.shaadi          1974 non-null   float64
 47  Phone Social Premium.skype           1974 non-null   float64
 48  Phone Social Premium.toi             1936 non-null   float64
 49  Phone Social Premium.whatsapp        262 non-null    float64
 50  Phone Social Premium.yatra           0 non-null      float64
 51  Phone Social Premium.zoho            1977 non-null   float64
 52  phone_digitalage                     2000 non-null   int64
 53  phone_nameMatchScore                 2000 non-null   float64
 54  phone_phoneFootprintStrengthOverall  1999 non-null   object
dtypes: bool(1), float64(22), int64(8), object(24)
memory usage: 845.8+ KB

In [7]:
#Checking whether the dataset has any null values
train_data.isnull().sum()

DEALER ID                                 0
APPLICATION LOGIN DATE                    0
HDB BRANCH NAME                           1
HDB BRANCH STATE                        854
FIRST NAME                                0
MIDDLE NAME                            7145
LAST NAME                               681
mobile                                    0
AADHAR VERIFIED                           0
Cibil Score                            4297
MOBILE VERIFICATION                       0
DEALER NAME                               4
TOTAL ASSET COST                       5108
ASSET CTG                              5108
ASSET MODEL NO                            0
APPLIED AMOUNT                            0
PRIMARY ASSET MAKE                        0
Primary Asset Model No                    0
Personal Email Address                    0
MARITAL STATUS                         4894
GENDER                                    0
DOB                                       0
AGE                                       0
ADDRESS TYPE                           3312
EMPLOY CONSTITUTION                    4998
EMPLOYER NAME                          5010
EMPLOYER TYPE                          4998
Pan Name                               1053
name                                      0
vpa                                    2787
upi_name                               2789
Phone Social Premium.a23games          9999
Phone Social Premium.amazon            1916
Phone Social Premium.byjus             1948
Phone Social Premium.flipkart          1832
Phone Social Premium.housing           1776
Phone Social Premium.indiamart         1775
Phone Social Premium.instagram         6630
Phone Social Premium.isWABusiness      8427
Phone Social Premium.jeevansaathi      1829
Phone Social Premium.jiomart           9590
Phone Social Premium.microsoft         1872
Phone Social Premium.my11              9998
Phone Social Premium.paytm             1757
Phone Social Premium.rummycircle       9999
Phone Social Premium.shaadi            1779
Phone Social Premium.skype             1785
Phone Social Premium.toi               1943
Phone Social Premium.whatsapp          8427
Phone Social Premium.yatra             9991
Phone Social Premium.zoho              1782
phone_digitalage                          4
phone_nameMatchScore                      4
phone_phoneFootprintStrengthOverall       6
Application Status                        0
dtype: int64

In [8]:
test_data.isnull().sum()

UID                                       0
DEALER ID                                 0
APPLICATION LOGIN DATE                    0
HDB BRANCH NAME                           0
HDB BRANCH STATE                        172
FIRST NAME                                0
MIDDLE NAME                            1405
LAST NAME                               131
mobile                                    0
AADHAR VERIFIED                           0
Cibil Score                             842
MOBILE VERIFICATION                       0
DEALER NAME                               0
TOTAL ASSET COST                       1022
ASSET CTG                              1022
ASSET MODEL NO                            0
APPLIED AMOUNT                            0
PRIMARY ASSET MAKE                        0
Primary Asset Model No                    0
Personal Email Address                    0
MARITAL STATUS                          981
GENDER                                    0
DOB                                       0
AGE                                       0
ADDRESS TYPE                            635
EMPLOY CONSTITUTION                     994
EMPLOYER NAME                           995
EMPLOYER TYPE                           994
Pan Name                                209
name                                      0
vpa                                     554
upi_name                                555
Phone Social Premium.a23games          2000
Phone Social Premium.amazon             117
Phone Social Premium.byjus               23
Phone Social Premium.flipkart            45
Phone Social Premium.housing             23
Phone Social Premium.indiamart           23
Phone Social Premium.instagram         1388
Phone Social Premium.isWABusiness      1738
Phone Social Premium.jeevansaathi        38
Phone Social Premium.jiomart           1957
Phone Social Premium.microsoft           29
Phone Social Premium.my11              2000
Phone Social Premium.paytm               25
Phone Social Premium.rummycircle       2000
Phone Social Premium.shaadi              26
Phone Social Premium.skype               26
Phone Social Premium.toi                 64
Phone Social Premium.whatsapp          1738
Phone Social Premium.yatra             2000
Phone Social Premium.zoho                23
phone_digitalage                          0
phone_nameMatchScore                      0
phone_phoneFootprintStrengthOverall       1
dtype: int64

In [9]:
drop_columns = ['DEALER ID', 'APPLICATION LOGIN DATE', 'FIRST NAME', 'MIDDLE NAME', 'LAST NAME', 'mobile', 
                'HDB BRANCH NAME', 'HDB BRANCH STATE']

In [10]:
#Dropped varibles that do not have impact to target variable
train_data_cleaned = train_data.drop(columns=drop_columns)
test_data_cleaned=test_data.drop(columns=drop_columns)

In [11]:
mixed_type_columns = []
for col in train_data_cleaned.columns:
    if train_data_cleaned[col].apply(lambda x: isinstance(x, (int, str))).any():
        mixed_type_columns.append(col)

mixed_type_columns

['AADHAR VERIFIED',
 'Cibil Score',
 'MOBILE VERIFICATION',
 'DEALER NAME',
 'ASSET CTG',
 'ASSET MODEL NO',
 'APPLIED AMOUNT',
 'PRIMARY ASSET MAKE',
 'Primary Asset Model No',
 'Personal Email Address',
 'MARITAL STATUS',
 'GENDER',
 'DOB',
 'AGE',
 'ADDRESS TYPE',
 'EMPLOY CONSTITUTION',
 'EMPLOYER NAME',
 'EMPLOYER TYPE',
 'Pan Name',
 'name',
 'vpa',
 'upi_name',
 'phone_phoneFootprintStrengthOverall',
 'Application Status']

In [12]:
#Convert columns with mixed data types to a single type(string)
mixed_type_columns = ['AADHAR VERIFIED',
                      'Cibil Score',
                      'MOBILE VERIFICATION',
                      'DEALER NAME',
                      'ASSET CTG',
                      'ASSET MODEL NO',
                      'APPLIED AMOUNT',
                      'PRIMARY ASSET MAKE',
                      'Primary Asset Model No',
                      'Personal Email Address',
                      'MARITAL STATUS',
                      'GENDER',
                      'DOB',
                      'AGE',
                      'ADDRESS TYPE',
                      'EMPLOY CONSTITUTION',
                      'EMPLOYER NAME',
                      'EMPLOYER TYPE',
                      'Pan Name',
                      'name',
                      'vpa',
                      'upi_name',
                      'phone_phoneFootprintStrengthOverall',
                      'Application Status']

# Convert these columns to strings
train_data_cleaned[mixed_type_columns] = train_data_cleaned[mixed_type_columns].astype(str)

In [13]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

label_encoder = LabelEncoder()

# Apply label encoding only for columns that are categorical
for col in train_data_cleaned.columns:
    if train_data_cleaned[col].dtype == 'object':
        train_data_cleaned[col] = label_encoder.fit_transform(train_data_cleaned[col].astype(str))

# Ensure that all data types are numeric after encoding
train_data_cleaned = train_data_cleaned.apply(pd.to_numeric, errors='coerce')


# Check if any remaining NaN values exist after conversion
if train_data_cleaned.isnull().values.any():
    train_data_cleaned = train_data_cleaned.fillna(-1)  # Fill any NaN values

# Split the data into features and target
X = train_data_cleaned.drop(columns=['Application Status'])
y = train_data_cleaned['Application Status']

# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the Random Forest model
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

# Validate the model
y_pred = rf_model.predict(X_val)
accuracy = accuracy_score(y_val, y_pred)

# Extract feature importance
feature_importances = rf_model.feature_importances_
features = X.columns

# Create a dataframe for feature importance ranking
feature_importance_df = pd.DataFrame({'Feature': features, 'Importance': feature_importances})
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False).reset_index(drop=True)

# Display model accuracy and top 10 important features
print(f"Model Accuracy: {accuracy * 100:.2f}%")
print("Top 10 Important Features:")
print(feature_importance_df.head(10))

Model Accuracy: 88.35%
Top 10 Important Features:
               Feature  Importance
0          Cibil Score    0.148200
1     TOTAL ASSET COST    0.086864
2        EMPLOYER TYPE    0.082410
3       MARITAL STATUS    0.077408
4  EMPLOY CONSTITUTION    0.077057
5            ASSET CTG    0.068447
6        EMPLOYER NAME    0.041016
7             Pan Name    0.036012
8         ADDRESS TYPE    0.034541
9                  DOB    0.028186

In [14]:
from xgboost import XGBClassifier

label_encoder = LabelEncoder()

# Apply label encoding only for columns that are categorical
for col in train_data_cleaned.columns:
    if train_data_cleaned[col].dtype == 'object':
        train_data_cleaned[col] = label_encoder.fit_transform(train_data_cleaned[col].astype(str))

# Ensure that all data types are numeric after encoding
train_data_cleaned = train_data_cleaned.apply(pd.to_numeric, errors='coerce')

# Check if any remaining NaN values exist after conversion
if train_data_cleaned.isnull().values.any():
    train_data_cleaned = train_data_cleaned.fillna(-1)  #Fill any NaN values

# Split the data into features and target
X = train_data_cleaned.drop(columns=['Application Status'])
y = train_data_cleaned['Application Status']

# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the XGBoost model
xgb_model = XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='mlogloss')
xgb_model.fit(X_train, y_train)

# Validate the model
y_pred = xgb_model.predict(X_val)
accuracy = accuracy_score(y_val, y_pred)

# Extract feature importance
feature_importances = xgb_model.feature_importances_
features = X.columns

# Create a dataframe for feature importance ranking
feature_importance_df = pd.DataFrame({'Feature': features, 'Importance': feature_importances})
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False).reset_index(drop=True)

# Display model accuracy and top 10 important features
print(f"Model Accuracy: {accuracy * 100:.2f}%")
print("Top 10 Important Features:")
print(feature_importance_df.head(10))

Model Accuracy: 88.45%
Top 10 Important Features:
                      Feature  Importance
0         EMPLOY CONSTITUTION    0.817453
1            TOTAL ASSET COST    0.109202
2                 Cibil Score    0.013769
3                    Pan Name    0.003588
4                      GENDER    0.003086
5  Phone Social Premium.byjus    0.002743
6                         AGE    0.002457
7          PRIMARY ASSET MAKE    0.002157
8              MARITAL STATUS    0.001988
9              APPLIED AMOUNT    0.001964

In [15]:
#for test data
mixed_type_columns = []
for col in test_data_cleaned.columns:
    if test_data_cleaned[col].apply(lambda x: isinstance(x, (int, str))).any():
        mixed_type_columns.append(col)

mixed_type_columns

['UID',
 'AADHAR VERIFIED',
 'Cibil Score',
 'MOBILE VERIFICATION',
 'DEALER NAME',
 'ASSET CTG',
 'ASSET MODEL NO',
 'APPLIED AMOUNT',
 'PRIMARY ASSET MAKE',
 'Primary Asset Model No',
 'Personal Email Address',
 'MARITAL STATUS',
 'GENDER',
 'DOB',
 'AGE',
 'ADDRESS TYPE',
 'EMPLOY CONSTITUTION',
 'EMPLOYER NAME',
 'EMPLOYER TYPE',
 'Pan Name',
 'name',
 'vpa',
 'upi_name',
 'phone_digitalage',
 'phone_phoneFootprintStrengthOverall']

In [16]:
#Convert columns with mixed data types to a single type (string)
mixed_type_columns = ['AADHAR VERIFIED',
                      'Cibil Score',
                      'MOBILE VERIFICATION',
                      'DEALER NAME',
                      'ASSET CTG',
                      'ASSET MODEL NO',
                      'APPLIED AMOUNT',
                      'PRIMARY ASSET MAKE',
                      'Primary Asset Model No',
                      'Personal Email Address',
                      'MARITAL STATUS',
                      'GENDER',
                      'DOB',
                      'AGE',
                      'ADDRESS TYPE',
                      'EMPLOY CONSTITUTION',
                      'EMPLOYER NAME',
                      'EMPLOYER TYPE',
                      'Pan Name',
                      'name',
                      'vpa',
                      'upi_name',
                      'phone_phoneFootprintStrengthOverall']

# Convert these columns to strings
test_data_cleaned[mixed_type_columns] = test_data_cleaned[mixed_type_columns].astype(str)

In [17]:
# Apply label encoding to categorical variables
for col in test_data_cleaned.columns:
    if test_data_cleaned[col].dtype == 'object':
        test_data_cleaned[col] = label_encoder.fit_transform(test_data_cleaned[col])

# Ensure the test data is in the correct numeric format
test_data_cleaned = test_data_cleaned.apply(pd.to_numeric, errors='coerce')

# Handle any missing values in the test data
test_data_cleaned = test_data_cleaned.fillna(-1)


# Drop the 'uid' column from the test data
test_data_cleaned = test_data_cleaned.drop(columns=['UID'])

# Ensure that the test data has the same features as the training data
X_test = test_data_cleaned[X_train.columns]

# Predict on the aligned test data
test_predictions = rf_model.predict(X_test)

loan_status_mapping = {0: 'Rejected', 1: 'Approved'}
test_data_cleaned['Loan_Status_Prediction'] = test_predictions
test_data_cleaned['Loan_Status_Prediction'] = test_data_cleaned['Loan_Status_Prediction'].map(loan_status_mapping)

# View the predictions
print(test_data_cleaned[['Loan_Status_Prediction']])

     Loan_Status_Prediction
0                  Rejected
1                  Rejected
2                  Rejected
3                  Approved
4                  Rejected
...                     ...
1995               Rejected
1996               Rejected
1997               Approved
1998               Rejected
1999               Rejected

[2000 rows x 1 columns]

In [19]:
import pandas as pd

# Convert predictions to 'Rejected' and 'Approved' using list comprehension
loan_status_mapping = {0: 'Rejected', 1: 'Approved'}
test_data_cleaned['Loan_Status_Prediction'] = [loan_status_mapping[pred] for pred in test_predictions]

# Ensure UID is treated as a string to avoid scientific notation issues
test_data_cleaned['UID'] = test_data['UID'].astype(str)

# Check for missing values in predictions
print(test_data_cleaned['Loan_Status_Prediction'].isnull().sum()) #Should return 0 if no missing values

# Create DataFrame with 'UID' and 'Loan_Status_Prediction'
submission_df = test_data_cleaned[['UID', 'Loan_Status_Prediction']]

# Save the UID in scientific notation when writing to CSV
submission_df['UID'] = submission_df['UID'].apply(lambda x: format(float(x), '.2E'))

# Save to CSV
submission_df.to_csv('predictions.csv', index=False)

print("Predictions saved successfully!")

0
Predictions saved successfully!